load('//Config:configs.bzl', 'library_configs', 'info_plist_substitutions')

apple_library(
  name = 'RedditAPI',
  modular = True,
  configs = library_configs(),
  exported_headers = glob([
    'Sources/**/*.h',
  ]),
  srcs = glob([
    'Sources/**/*.m',
  ]),
  extra_xcode_files = [
    'RedditAPI.modulemap',
  ],
  visibility = ['PUBLIC'],
)
