load('//Config:configs.bzl', 'binary_configs', 'info_plist_substitutions')

apple_binary(
  name = 'AppBinary',
  configs = binary_configs('Reddit'),
  srcs = glob([
    'Sources/*.swift',
  ]),
)

apple_bundle(
  name = 'Reddit',
  binary = ':AppBinary',
  extension = 'app',
  info_plist = 'Info.plist',
  info_plist_substitutions = info_plist_substitutions('Reddit'),
)

apple_package(
  name = "RedditApp",
  bundle = ":Reddit",
)

xcode_workspace_config(
  name = "workspace",
  workspace_name = "Reddit",
  src_target = ":Reddit",
  additional_scheme_actions = {
      "Build": {
          "PRE_SCHEME_ACTIONS": ["echo 'Started'"],
          "POST_SCHEME_ACTIONS": ["echo 'Finished'"],
      },
  },
  action_config_names = {"profile": "Profile"},
)
